name: Generate Prototypes

on:
  push:
    branches:
      - main
      - dev

jobs:
  generate_prototypes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        id: runscript
        run: python scripts/todo.py
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true

      - name: Create Pull Request
        if: steps.runscript.outcome == 'success'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Add generated prototypes
          title: Add generated prototypes
          branch: prototypes