name: Generate Prototypes and Create PR

on:
  push:
    branches:
      - main
      - dev

jobs:
  generate_prototypes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python scripts/todo.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Add generated prototypes" || echo "No changes to commit."
          git push origin HEAD:prototypes || echo "No changes to push."

      - name: Create Pull Request
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"head":"prototypes", "base":"main", "title":"New Prototypes", "body":"Generated new prototypes."}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls"
