name: Generate Prototypes

on:
  push:
    branches:
      - dev

jobs:
  generate_prototypes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  # checkout the branch that triggered the workflow
          token: ${{ secrets.PAT }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        id: runscript
        run: python scripts/todo.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true

      - name: Create Pull Request using curl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/somewheresy/somewhere-prototyping-agent/pulls \
          -d '{
            "title": "Add prototypes based on @TODO",
            "head": "prototyping",
            "base": "dev"
          }'