name: Generate Prototypes

on:
  push:
    branches:
      - main
      - dev

jobs:
  generate_prototypes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  # checkout the branch that triggered the workflow

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        id: runscript
        run: python scripts/todo.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --cached --exit-code || git commit -m "[Auto] Generate Prototypes for @TODO tasks in /prototypes"
          git push origin ${{ github.head_ref }} || echo "No changes to commit."
